replicaCount: 1

image:
  repository: apache/nifi
  tag: 2.3.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080
  httpsPort: 8443

resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

persistence:
  enabled: true
  size: 10Gi
  storageClass: ""

nifi:
  cluster:
    enabled: false
  properties:
    nifi_web_http_port: 8080
    nifi_web_https_port: 8443

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: nifi.local
      paths: ["/"]
  tls: []
