apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mongodb-ironbank.fullname" . }}
  labels:
    app: {{ include "mongodb-ironbank.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "mongodb-ironbank.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "mongodb-ironbank.name" . }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
        - name: mongodb
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 27017
              name: mongodb
          env:
            - name: MONGODB_ROOT_USER
              value: {{ .Values.auth.rootUser | quote }}
            - name: MONGODB_ROOT_PASSWORD
              value: {{ .Values.auth.rootPassword | quote }}
          volumeMounts:
            - name: mongodb-storage
              mountPath: /data/db
      volumes:
        - name: mongodb-storage
          persistentVolumeClaim:
            claimName: {{ include "mongodb-ironbank.fullname" . }}
