---
apiVersion: v2
name: nifi
version: 0.6.19
appVersion: 2.3.0-custom
description: Apache NiFi From Zapata Technology IRONBANK
keywords:
  - nifi
  - data
  - process
home: https://nifi.apache.org/
icon: https://svn.apache.org/repos/asf/nifi/site/trunk/images/niFi-logo-horizontal-scaled.png
maintainers:
  - name: Drew
    email: drew@zapatatechnology.com
    url: https://github.com/ferrelburn

dependencies:
  - name: zookeeper
    version: 9.2.7
    repository: https://charts.bitnami.com/bitnami
    condition: zookeeper.enabled
  - name: ca
    version: 1.0.1
    condition: ca.enabled
  - name: openldap
    version: ~1.2.4
    repository: https://charts.helm.sh/stable
    condition: openldap.enabled