apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "grafana-ironbank.fullname" . }}
  labels:
    app: {{ include "grafana-ironbank.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "grafana-ironbank.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "grafana-ironbank.name" . }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
        - name: grafana
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
              name: http
          volumeMounts:
            - name: grafana-storage
              mountPath: /var/lib/grafana
      volumes:
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: {{ include "grafana-ironbank.fullname" . }}