apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nifi.fullname" . }}-config
data:
  nifi.properties: |
    nifi.web.http.port={{ .Values.nifi.properties.nifi_web_http_port }}
    nifi.web.https.port={{ .Values.nifi.properties.nifi_web_https_port }}
    nifi.security.user.login.identity.provider={{- if .Values.auth.ldap.enabled }}ldap-provider{{- else if .Values.auth.kerberos.enabled }}kerberos-provider{{- else if .Values.auth.singleUser.enabled }}single-user-provider{{- else }}{{ fail "No identity provider enabled in auth config!" }}{{- end }}

  login-identity-providers.xml: |-
    <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
    <loginIdentityProviders>

        {{- if .Values.auth.singleUser.enabled }}
        <provider>
            <identifier>single-user-provider</identifier>
            <class>org.apache.nifi.authentication.single.user.SingleUserLoginIdentityProvider</class>
            <property name="Username">{{ .Values.auth.singleUser.username }}</property>
            <property name="Password">{{ .Values.auth.singleUser.password }}</property>
        </provider>
        {{- end }}

        {{- if .Values.auth.ldap.enabled }}
        <provider>
            <identifier>ldap-provider</identifier>
            <class>org.apache.nifi.ldap.LdapProvider</class>
            <property name="Authentication Strategy">{{ .Values.auth.ldap.authStrategy }}</property>
            <property name="Manager DN">{{ .Values.auth.ldap.admin }}</property>
            <property name="Manager Password">{{ .Values.auth.ldap.pass }}</property>
            <property name="TLS - Keystore">{{ .Values.auth.ldap.keystore }}</property>
            <property name="TLS - Keystore Password">{{ .Values.auth.ldap.keystorePasswd }}</property>
            <property name="TLS - Keystore Type">{{ .Values.auth.ldap.keystoreType }}</property>
            <property name="TLS - Truststore">{{ .Values.auth.ldap.truststore }}</property>
            <property name="TLS - Truststore Password">{{ .Values.auth.ldap.truststorePasswd }}</property>
            <property name="TLS - Truststore Type">{{ .Values.auth.ldap.truststoreType }}</property>
            <property name="TLS - Client Auth">{{ .Values.auth.ldap.clientAuth }}</property>
            <property name="TLS - Protocol">TLS</property>
            <property name="TLS - Shutdown Gracefully">false</property>
            <property name="Referral Strategy">FOLLOW</property>
            <property name="Connect Timeout">10 secs</property>
            <property name="Read Timeout">10 secs</property>
            <property name="Url">{{ .Values.auth.ldap.host }}</property>
            <property name="User Search Base">{{ .Values.auth.ldap.searchBase }}</property>
            <property name="User Search Filter">({{ .Values.auth.ldap.userIdentityAttribute }}={0})</property>
            <property name="Identity Strategy">{{ .Values.auth.ldap.identityStrategy }}</property>
            <property name="Authentication Expiration">{{ .Values.auth.ldap.authExpiration }}</property>
        </provider>
        {{- end }}

        {{- if .Values.auth.kerberos.enabled }}
        <provider>
            <identifier>kerberos-provider</identifier>
            <class>org.apache.nifi.kerberos.KerberosProvider</class>
            <property name="Default Realm">{{ .Values.auth.kerberos.realm }}</property>
            <property name="Authentication Expiration">{{ .Values.auth.kerberos.authExpiration }}</property>
        </provider>
        {{- end }}

    </loginIdentityProviders>
