replicaCount: 1

image:
  repository: registry1.dso.mil/ironbank/opensource/apache/nifi-registry
  tag: "2.3.0"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ironbank-creds

service:
  type: ClusterIP
  port: 18080

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
