replicaCount: 1

image:
  repository: registry1.dso.mil/ironbank/opensource/apache/nifi-registry
  tag: "2.3.0"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ironbank-creds

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 5Gi
  storageClassName: ""  # Use default storage class

service:
  type: NodePort
  nodePort: 31880  # Public-facing port used for HTTPS (maps to container port 18443)

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

tls:
  enabled: true
  secretName: nifi-registry-tls
  keystoreFilename: keystore.p12
  keystorePasswordKey: keystorePassword
  keystoreType: PKCS12
  httpsPort: 18443  # Internal container port exposed via service
