replicaCount: 1

image:
  repository: registry1.dso.mil/ironbank/opensource/apache/nifi-registry
  tag: "2.3.0"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ironbank-creds

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 5Gi
  storageClassName: ""  # Set to "" to use the default storage class

service:
  type: NodePort  # or LoadBalancer if you want a public IP
  port: 18080
  nodePort: 31880  # choose an available port above 30000

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
