apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nifi-registry.fullname" . }}
  labels:
    app: {{ include "nifi-registry.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "nifi-registry.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "nifi-registry.name" . }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
        - name: nifi-registry
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 18080
              name: http
          env:
            - name: NIFI_REGISTRY_WEB_HTTP_PORT
              value: "18080"
          volumeMounts:
            - name: flow-storage
              mountPath: /opt/nifi-registry/nifi-registry-current/flow_storage
      volumes:
        - name: flow-storage
          persistentVolumeClaim:
            claimName: {{ include "nifi-registry.fullname" . }}
