apiVersion: v1
kind: Service
metadata:
  name: {{ include "nifi-registry.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 18080
      protocol: TCP
      name: http
  selector:
    app: {{ include "nifi-registry.name" . }}
