apiVersion: v1
kind: Service
metadata:
  name: {{ include "nifi-registry.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.tls.httpsPort }}
      targetPort: {{ .Values.tls.httpsPort }}
      protocol: TCP
      name: https
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    app: {{ include "nifi-registry.name" . }}
