apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "prometheus-fips.fullname" . }}
  labels:
    app: {{ include "prometheus-fips.name" . }}
spec:
  serviceName: {{ include "prometheus-fips.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "prometheus-fips.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "prometheus-fips.name" . }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
        - name: prometheus
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 9090
              name: web
          volumeMounts:
            - name: prometheus-storage
              mountPath: /prometheus
  volumeClaimTemplates:
    - metadata:
        name: prometheus-storage
      spec:
        accessModes:
          - {{ .Values.persistence.accessMode }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
        {{- if .Values.persistence.storageClassName }}
        storageClassName: {{ .Values.persistence.storageClassName }}
        {{- end }}
