replicaCount: 1

image:
  repository: registry1.dso.mil/ironbank/opensource/grafana/grafana
  tag: "11.6.0"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ironbank-creds

service:
  type: NodePort
  port: 3000
  nodePort: 32000

resources: {}

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 10Gi
  storageClassName: ""


adminUser: admin
adminPassword: admin12345

ingress:
  enabled: true
  className: ""
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: grafana.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - grafana.local
      secretName: grafana-tls